apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- route.yaml
- service.yaml


secretGenerator:
- name: alertmanager-login
  files: 
  - alertmanager.env
- name: bot-config
  files:
  - botconfig.env

generatorOptions:
 disableNameSuffixHash: true
